---
title: "LGBmT Master Coding Doc"
output: html_notebook
---

```{r Libraries}
library(tidyverse) # general language library
library(ggplot2) # for easier plotting
library(leaflet) # also for mapping
library(sf) # for mapping
```

# Color Palettes + Data Loading
```{r color palettes, echo=FALSE}
safe_colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", 
                             "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")
```

```{r load in map of SF}
# load in SF map data (via sf package)

#geojson file from https://github.com/MissionLocal/interactives/blob/main/docs/redistricting-map-final/FinalDraftMap.geojson
# We edited file to remove duplicate / extra district areas
sf_district_map_clean <- st_read("/Users/olivercollado/Library/CloudStorage/OneDrive-Personal/Work.Academic/R Files/Spring 2025 Propel Stats Class/masterS_files/FinalDraftMap_copy.geojson")

sf_district_map_clean$DISTRICT <- factor(sf_district_map_clean$DISTRICT , levels=c('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'))

#fixed file here removes extra labels
ggplot(sf_district_map_clean) +
  geom_sf(color = "black",aes(fill = factor(DISTRICT)), show.legend = FALSE) +
  scale_fill_manual(values = safe_colorblind_palette, name= "SF District") +
  geom_sf_label(aes(label = DISTRICT)) +
  theme_void()
```

```{r csv loading and formatting}
#load in our data
sf_housing_data <- read_csv("sf_clean.csv")

# add new price_per_sqft column
sf_housing_data <- sf_housing_data %>%
  mutate(price_per_sqft = (price/sqft)) %>%
  print()

# rename column for inner_join later on
 sf_housing_data <- rename(sf_housing_data, DISTRICT = hood_district)

```



# Choos Data
```{r average rent grouped by beds}
avg_rent_beds <- sf_housing_data %>%
  group_by(beds) %>%
  summarize(avg_rent = mean(price, na.rm = TRUE), .groups = "drop") %>%
  print()
```

```{r comparison table of average rooms and district}
avg_rent_table <- sf_housing_data %>%
  group_by(beds, DISTRICT) %>%
  summarize(avg_rent = mean(price, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(
    names_from = DISTRICT,
    values_from = avg_rent,
    names_prefix = "District_"
  )

print(avg_rent_table)

```


# Stat Tests
## Inferential Statistics 
Check to see if these prices are statistically significant, for example with 1bedroom.

```{r 1bed results}
df_1bed <- sf_housing_data %>% filter(beds == 1)

table(df_1bed$DISTRICT)

anova_result <- aov(price ~ factor(DISTRICT), data = df_1bed)

summary(anova_result)
```

## Descriptive Statistics
```{r Summaries by District}
list <- c('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11')

for(district in list) {
  district_summary <- sf_housing_data %>% 
    filter(DISTRICT == district) %>%
    select(price, sqft, price_per_sqft, beds, bath) %>%
    summary() %>%
    print()
}
```

```{r 1-Bedroom Summaries by District}
list <- c('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11')

for(district in list) {
  district_summary <- sf_housing_data %>% 
    filter(DISTRICT == district, beds == 1) %>%
    select(price, sqft, price_per_sqft, beds, bath) %>%
    summary() %>%
    print()
}
```

#Data Cleaning
```{r for figures}
# to define district order
sf_housing_data$DISTRICT <- factor(sf_housing_data$DISTRICT , levels=c('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11'))

# to see districts as characters, not numbers
sf_housing_data$DISTRICT <- as.character(sf_housing_data$DISTRICT)

#summary across districts
sf_housing_data %>%
  group_by(DISTRICT) %>%
  summarise(avg_ppsf = mean(price_per_sqft),avg_price = mean(price),avg_sf = mean(sqft), avg_bed = mean(beds), avg_bath = mean(bath)) %>%
  print()
```

```{r for maps}
#summary across districts
sf_district_housing_summary <- sf_housing_data %>%
  group_by(DISTRICT) %>%
  summarise(avg_ppsf = mean(price_per_sqft),avg_price = mean(price),avg_sf = mean(sqft), avg_bed = mean(beds), avg_bath = mean(bath))

#summary for 1 bed units across districts
sf_district_housing_summary_1bed <- sf_housing_data %>%
  group_by(DISTRICT) %>%
  filter(beds == "1") %>%
  summarise(avg_ppsf = mean(price_per_sqft),avg_price = mean(price),avg_sf = mean(sqft), avg_bed = mean(beds), avg_bath = mean(bath))

# count of 1beds by district
sf_1bed_count <- df_1bed %>%
  count(DISTRICT) %>%
  mutate(count = n) %>%
  mutate(n = c())

# to see districts as characters, not numbers
sf_1bed_count$DISTRICT <- as.character(sf_1bed_count$DISTRICT)

#make one master district file for all units
sf_district_map_summary <- sf_district_map_clean %>%
  inner_join(sf_district_housing_summary, by = "DISTRICT")

#make one master district file for 1bed units
sf_district_map_summary_1bed <- sf_district_map_clean %>%
  inner_join(sf_district_housing_summary_1bed, by = "DISTRICT") %>%
  inner_join(sf_1bed_count, by = "DISTRICT")

```

# Visualizations
## Bar Graphs
```{r Rent by bedrooms}
# bar graph
ggplot(avg_rent_beds, aes(x = factor(beds), y = avg_rent, fill = factor(beds))) +
  geom_col() +
  labs(
    title = "Average Rent by Number of Bedrooms",
    x = "Bedrooms",
    y = "Average Rent (USD)",
    fill = "Bedrooms"
  ) +
  theme_minimal()
```

```{r Rent by district} 
# bar graph
ggplot(sf_district_housing_summary, aes(x = factor(DISTRICT), y = avg_price, fill = factor(DISTRICT))) +
  geom_col() +
  labs(
    title = "Average Rent by District",
    x = "District",
    y = "Average Rent (USD)",
    fill = "Price"
  ) +
  theme_minimal()
```

```{r Average 1b rent by District}
ggplot(sf_district_housing_summary_1bed, aes(x = factor(DISTRICT), y = avg_price, fill = factor(DISTRICT))) +
  geom_col() +
  labs(
    title = "Average 1-Bedroom Rent by District",
    x = "District",
    y = "Average Rent (USD)",
    fill = "Price"
  ) +
  theme_minimal()
```



#SF Map overlays
```{r SF mapping}
# let's see if we can map some shit

# mapping raw price by district
ggplot(sf_district_map_summary) +
  geom_sf(color = "black",aes(fill = avg_price), show.legend = TRUE) +
  geom_sf_label(aes(label = DISTRICT)) +
  scale_fill_gradient(low = "lavender", high = "#a661d3") +
  theme_void() +
  labs(title = "Average Price for all Housing by District",
       subtitle = "District 4 is the most expensive by raw price")

# mapping raw 1bed price by district
ggplot(sf_district_map_summary_1bed) +
  geom_sf(color = "black",aes(fill = avg_price), show.legend = TRUE) +
  geom_sf_label(aes(label = DISTRICT)) +
  scale_fill_gradient(low = "lavender", high = "#a661d3") +
  theme_void() +
  labs(title = "Average Price for 1 unit Housing by District",
       subtitle = "District 7 is the most expensive by raw price ")
  

# mapping number of 1beds by district
ggplot(sf_district_map_summary_1bed) +
  geom_sf(color = "black",aes(fill = count), show.legend = TRUE) +
  geom_sf_label(aes(label = DISTRICT)) +
  scale_fill_gradient(low = "lavender", high = "#a661d3") +
  theme_void() +
  labs(title = "Amount of 1 bed units by District",
       subtitle = "District 9 has the most available units at this time")
```
